name: ci

on:
  push:
    branches:
      - 'master'
      - 'main'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        uses: actions/checkout@master
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./app
          file: ./app/Dockerfile.prod
          pull: true
          push: true
          build-args: |
            arg1=value1
            arg2=value2
          cache-from: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/${{ github.event.repository.name }}:latest
          cache-to: type=inline
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ github.event.repository.name }}:latest,${{ secrets.DOCKERHUB_USERNAME }}/${{ github.event.repository.name }}:${{ github.sha }}
      -
        name: executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@master
        with:
          host: 138.68.129.97
          username: root
          key: ${{ secrets.DOCKER_SSH_PRIVATE_KEY }}
          script: whoami
