name: ci

on:
  push:
    branches:
      - 'master'
      - 'main'

jobs:
  docker-build-and-publish:
    name: docker-build-and-publish
    runs-on: ubuntu-latest
    steps:
      -
        uses: actions/checkout@master
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./app
          file: ./app/Dockerfile.prod
          pull: true
          push: true
          build-args: |
            arg1=value1
            arg2=value2
          cache-from: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/${{ github.event.repository.name }}:latest
          cache-to: type=inline
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ github.event.repository.name }}:latest,${{ secrets.DOCKERHUB_USERNAME }}/${{ github.event.repository.name }}:${{ github.sha }}
  deploy:
    name: docker-compose-deploy
    runs-on: ubuntu-latest
    needs: docker-build-and-publish
    steps:
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Deploy to server
        uses: wshihadeh/docker-deployment-action@v1
        with:
          remote_docker_host: root@138.68.129.97
          ssh_private_key: ${{ secrets.DOCKER_SSH_PRIVATE_KEY }}
          ssh_public_key: ${{ secrets.DOCKER_SSH_PUBLIC_KEY }}
          deployment_mode: docker-compose
          copy_stack_file: true
          pull_images_first: true
          deploy_path: /root/app
          stack_file_name: docker-compose.prod.yml
          keep_files: 5
          args: up -d
